services:
  - type: web
    name: connect-io-messenger
    env: python
    region: oregon
    plan: free
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
      echo "✅ Dependencies installed"
    startCommand: |
      chmod +x startup.sh
      ./startup.sh
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: messenger-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: RENDER
        value: true
      - key: PYTHONUNBUFFERED
        value: 1
      - key: DISABLE_COLLECTSTATIC
        value: 0
    disk:
      name: media
      mountPath: /opt/render/project/src/media
      sizeGB: 1
    healthCheckPath: /health-check/
    autoDeploy: true

databases:
  - name: messenger-db
    plan: free
    region: oregon