services:
  - type: web
    name: messenger-app
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate --no-input
    startCommand: chmod +x startup.sh && ./startup.sh
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: messenger-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: messenger-db
    plan: free