# Generated by Django 4.2.26 on 2026-02-26 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmedia',
            name='waveform',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='voice_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='voice_waveform',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userstatus',
            name='is_recording_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recording_users_status', to='chat.conversation'),
        ),
        migrations.AlterField(
            model_name='chatmedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('voice', 'Voice Message'), ('document', 'Document'), ('sticker', 'Sticker'), ('gif', 'GIF')], max_length=10),
        ),
        migrations.AlterField(
            model_name='chatnotification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'New Message'), ('call', 'Incoming Call'), ('group_invite', 'Group Invitation'), ('mention', 'Mention'), ('reaction', 'Message Reaction'), ('reply', 'Message Reply'), ('voice', 'Voice Message'), ('system', 'System Notification')], max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('voice', 'Voice Message'), ('file', 'File'), ('emoji', 'Emoji')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='status',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('typing', 'Typing...'), ('recording', 'Recording...'), ('away', 'Away'), ('busy', 'Busy')], default='offline', max_length=20),
        ),
    ]
