# Generated by Django 5.2.7 on 2025-10-14 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_conversationsettings_messagereaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='conversationsettings',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='conversationsettings',
            name='conversation',
        ),
        migrations.RemoveField(
            model_name='conversationsettings',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='messagereaction',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='messagereaction',
            name='message',
        ),
        migrations.RemoveField(
            model_name='messagereaction',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='chatnotification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='groupinvitation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
        migrations.RemoveIndex(
            model_name='chatnotification',
            name='chat_chatno_user_id_6494da_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatnotification',
            name='chat_chatno_created_635191_idx',
        ),
        migrations.RemoveIndex(
            model_name='chatnotification',
            name='chat_chatno_notific_94b5e8_idx',
        ),
        migrations.RemoveIndex(
            model_name='conversation',
            name='chat_conver_is_grou_154d14_idx',
        ),
        migrations.RemoveIndex(
            model_name='conversation',
            name='chat_conver_created_656b50_idx',
        ),
        migrations.RemoveIndex(
            model_name='conversation',
            name='chat_conver_is_acti_72f866_idx',
        ),
        migrations.RemoveIndex(
            model_name='groupinvitation',
            name='chat_groupi_invited_a904a6_idx',
        ),
        migrations.RemoveIndex(
            model_name='groupinvitation',
            name='chat_groupi_expires_934f4b_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='chat_messag_convers_cd68de_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='chat_messag_sender__b20cde_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='chat_messag_is_read_872c73_idx',
        ),
        migrations.RemoveField(
            model_name='chatnotification',
            name='action_url',
        ),
        migrations.RemoveField(
            model_name='chatnotification',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='groupinvitation',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='groupinvitation',
            name='message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='file_attachment',
        ),
        migrations.RemoveField(
            model_name='message',
            name='image_attachment',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_type',
        ),
        migrations.AlterField(
            model_name='chatnotification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'New Message'), ('typing', 'Typing Indicator'), ('online', 'Online Status'), ('group_invite', 'Group Invitation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='groupinvitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='userstatus',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ConversationSettings',
        ),
        migrations.DeleteModel(
            name='MessageReaction',
        ),
    ]
