# Generated by Django 4.2.7 on 2025-10-12 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_message_edited_at_message_is_edited_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='is_edited',
            new_name='is_read',
        ),
        migrations.RenameField(
            model_name='userstatus',
            old_name='last_activity',
            new_name='last_seen',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='group_admin',
        ),
        migrations.RemoveField(
            model_name='message',
            name='edited_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='file',
        ),
        migrations.RemoveField(
            model_name='message',
            name='reactions',
        ),
        migrations.RemoveField(
            model_name='message',
            name='read',
        ),
        migrations.RemoveField(
            model_name='message',
            name='read_by',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Call',
        ),
    ]
