# Generated by Django 4.2.7 on 2025-10-12 07:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_alter_conversation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='typing_users',
            field=models.ManyToManyField(blank=True, related_name='typing_in_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
