# Generated by Django 5.2.7 on 2025-10-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_message_file_message_file_name_message_file_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('file', 'File'), ('audio', 'Audio'), ('emoji', 'Emoji')], default='text', max_length=10),
        ),
    ]
