# Generated by Django 4.2.26 on 2026-02-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
