# Generated by Django 5.2.7 on 2025-10-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userstatus_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstatus',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='invitation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='socialaccount',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='accounts_cu_usernam_ab560e_idx',
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='accounts_cu_email_5ce40b_idx',
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='accounts_cu_phone_n_908ea4_idx',
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='accounts_cu_online__c78e23_idx',
        ),
        migrations.RemoveIndex(
            model_name='invitation',
            name='accounts_in_token_be8e6c_idx',
        ),
        migrations.RemoveIndex(
            model_name='invitation',
            name='accounts_in_expires_0319bc_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='accounts_no_user_id_a4ff2e_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='accounts_no_created_caf92d_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='accounts_no_notific_6d2f3e_idx',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='is_favorite',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='blocked_users',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='token',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_object_id',
        ),
        migrations.RemoveField(
            model_name='socialaccount',
            name='extra_data',
        ),
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'New Message'), ('friend_request', 'Friend Request'), ('invitation', 'Invitation'), ('system', 'System'), ('group', 'Group Message')], max_length=20),
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='provider',
            field=models.CharField(choices=[('google', 'Google'), ('facebook', 'Facebook')], max_length=20),
        ),
        migrations.DeleteModel(
            name='UserStatus',
        ),
    ]
