# Generated by Django 4.2.26 on 2025-12-19 17:24

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_profile_picture_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=accounts.models.user_profile_picture_path),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
