# Generated by Django 5.2.7 on 2025-10-14 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_userstatus_user_alter_contact_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='desktop_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='friend_online_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='friend_request_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='group_mentions_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='group_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='marketing_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='message_preview',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='message_sound',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='quiet_hours_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='quiet_hours_end',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='quiet_hours_start',
            field=models.TimeField(default='22:00'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='system_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_buttons',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'New Message'), ('friend_request', 'Friend Request'), ('invitation', 'Invitation'), ('system', 'System'), ('group', 'Group Message'), ('message_reaction', 'Message Reaction'), ('message_edit', 'Message Edited'), ('online_status', 'Online Status')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read', 'created_at'], name='accounts_no_user_id_cabb0a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'notification_type'], name='accounts_no_user_id_65e69b_idx'),
        ),
    ]
