# Generated by Django 4.2.26 on 2025-12-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='verification_sid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
