# Generated by Django 5.2.7 on 2025-10-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_friendrequest_friendship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='quiet_hours_end',
            field=models.TimeField(blank=True, default='08:00', null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='quiet_hours_start',
            field=models.TimeField(blank=True, default='22:00', null=True),
        ),
    ]
