# Generated by Django 4.2.26 on 2025-11-23 05:18

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_quiet_hours_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=accounts.models.user_profile_picture_path),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='quiet_hours_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='quiet_hours_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
