# Generated by Django 4.2.26 on 2025-12-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_passwordresetotp_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='verification_sid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
